
(function(){
'use strict';
const P={version:'2.17',teacherCode:'123456',badgeFiles:['assets/badges/badge-process.png','assets/badges/badge-speech.png','assets/badges/badge-heritage.png']};
const safeParse=(s,d=null)=>{try{return JSON.parse(s)}catch(e){return d}};
const b64e=o=>{const s=encodeURIComponent(JSON.stringify(o)).replace(/%([0-9A-F]{2})/g,(_,p)=>String.fromCharCode('0x'+p));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')};
const b64d=s=>{try{s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const raw=atob(s);let pct='';for(let i=0;i<raw.length;i++)pct+='%'+raw.charCodeAt(i).toString(16).padStart(2,'0');return JSON.parse(decodeURIComponent(pct))}catch(e){return null}};
function getSession(){return safeParse(localStorage.getItem('platformSession'),null)}
function setSession(s){localStorage.setItem('platformSession',JSON.stringify(s));if(s&&s.role==='student'&&s.student){['currentStudent','studentInfo','activeStudent','loginStudent'].forEach(k=>localStorage.setItem(k,JSON.stringify(s.student)))}if(s&&s.role==='teacher'){localStorage.setItem('teacherMode','true')}}
function clearSession(){localStorage.removeItem('platformSession');localStorage.removeItem('teacherMode');['currentStudent','studentInfo','activeStudent','loginStudent'].forEach(k=>localStorage.removeItem(k))}
function currentStudent(){return safeParse(localStorage.getItem('currentStudent'),null)}
function studentKey(st=currentStudent()){return st?`${st.cls}-${st.seat}-${st.name}`:''}
function genPass(st){const key=`${st.cls}|${st.seat}|${st.name}`;let h=2166136261;for(const ch of key){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}const year=new Date().getFullYear();return `FX-${year}-${String(Math.abs(h)%1000000).padStart(6,'0')}`}
function upsertStudent(st){if(!st)return null;const list=safeParse(localStorage.getItem('students'),'[]')||[];st.key=st.key||studentKey(st);st.passNumber=st.passNumber||genPass(st);st.grade=st.grade||extractGrade(st.cls);st.lastLogin=new Date().toLocaleString();const i=list.findIndex(x=>x.key===st.key);if(i>=0)list[i]={...list[i],...st};else list.push(st);localStorage.setItem('students',JSON.stringify(list));return st}
function extractGrade(cls=''){const m=String(cls).match(/(七|八|九|初一|初二|初三|高一|高二|高三|\d+)年?级?/);return m?m[0]:'未分年级'}
function applyUrlSession(){const q=new URLSearchParams(location.search),tok=q.get('session');if(!tok)return;const s=b64d(tok);if(!s||!s.role)return;setSession(s);q.delete('session');history.replaceState({},'',location.pathname+(q.toString()?('?'+q):'')+location.hash)}
applyUrlSession();
window.MTP2={
 getSession,setSession,clearSession,currentStudent,studentKey,genPass,upsertStudent,
 isTeacher:()=>getSession()?.role==='teacher'||localStorage.getItem('teacherMode')==='true',
 shareLink(){const s=getSession();if(!s)return alert('请先登录后再生成分享链接。');const url=new URL(location.href);url.searchParams.set('session',b64e(s));navigator.clipboard?.writeText(url.href).then(()=>alert('已复制保持登录状态的分享链接。\n注意：教师分享链接相当于分享教师权限，请谨慎使用。')).catch(()=>prompt('复制下面的分享链接：',url.href));},
 logout(){clearSession();location.href='index.html'},
 badgeKey(n){const k=studentKey();return k?`badge${n}:${k}`:`badge${n}`},
 getBadge(n){return localStorage.getItem(this.badgeKey(n))==='unlocked'||localStorage.getItem(`badge${n}`)==='unlocked'},
 unlockBadge(n){localStorage.setItem(this.badgeKey(n),'unlocked');localStorage.setItem(`badge${n}`,'unlocked');this.syncStudentSnapshot()},
 thinkingStarKey(){const k=studentKey();return k?`thinkingStar:${k}`:''},
 getThinkingStar(){const k=this.thinkingStarKey();return !!k&&localStorage.getItem(k)==='unlocked'},
 unlockThinkingStar(){const k=this.thinkingStarKey();if(!k)return false;localStorage.setItem(k,'unlocked');this.syncStudentSnapshot();document.dispatchEvent(new CustomEvent('mengxiThinkingStarUnlocked'));return true},
 syncStudentSnapshot(){const st=currentStudent();if(!st)return;const list=safeParse(localStorage.getItem('students'),'[]')||[];const i=list.findIndex(x=>x.key===studentKey(st));const snap={...st,badges:[1,2,3].map(n=>this.getBadge(n)),thinkingStar:this.getThinkingStar(),lastSeen:new Date().toLocaleString()};if(i>=0)list[i]={...list[i],...snap};else list.push(snap);localStorage.setItem('students',JSON.stringify(list));}
};
function restoreStudentBadges(){const st=currentStudent();if(!st)return;const rec=(safeParse(localStorage.getItem('students'),'[]')||[]).find(x=>x.key===studentKey(st));if(rec&&Array.isArray(rec.badges))rec.badges.forEach((v,i)=>{if(v){localStorage.setItem(`badge${i+1}:${studentKey(st)}`,'unlocked');localStorage.setItem(`badge${i+1}`,'unlocked')}else localStorage.removeItem(`badge${i+1}`)})}
restoreStudentBadges();
function patchFunctions(){
 if(typeof window.saveStudentEverywhere==='function'){const old=window.saveStudentEverywhere;window.saveStudentEverywhere=function(st){st=upsertStudent(st);old(st);setSession({role:'student',student:st,loginAt:new Date().toISOString()});restoreStudentBadges();return st}}
 if(typeof window.setStudent==='function'){const old=window.setStudent;window.setStudent=function(st){st=upsertStudent(st);old(st);setSession({role:'student',student:st,loginAt:new Date().toISOString()});restoreStudentBadges();return st}}
 if(typeof window.saveProgress==='function'){const old=window.saveProgress;window.saveProgress=function(page,detail={}){old(page,detail);const st=currentStudent();if(st){const logs=safeParse(localStorage.getItem('studentActivity'),'[]')||[];logs.push({studentKey:studentKey(st),passNumber:st.passNumber,page,detail,time:new Date().toLocaleString(),ts:Date.now()});localStorage.setItem('studentActivity',JSON.stringify(logs));MTP2.syncStudentSnapshot()}return true}}
 if(typeof window.logout==='function'){window.logout=function(){MTP2.logout()}}
}
function moveNavIntoHero(){const hero=document.querySelector('.hero'),nav=document.querySelector('.site-nav-shell');if(hero&&nav&&nav.parentElement!==hero)hero.appendChild(nav)}
function addUserBar(){if(location.pathname.endsWith('index.html')||location.pathname.endsWith('/')||document.querySelector('.v2-userbar'))return;const s=getSession();const bar=document.createElement('div');bar.className='v2-userbar';let left='尚未登录';if(s?.role==='teacher')left='<span class="v2-teacher-flag">教师模式：全部展馆已解锁</span>';else if(s?.role==='student'&&s.student)left=`已登录：<b>${escapeHtml(s.student.cls)} ${escapeHtml(s.student.seat)}号 ${escapeHtml(s.student.name)}</b>　探展编号：<b>${escapeHtml(s.student.passNumber||'')}</b>${MTP2.getThinkingStar()?'<span class="v2-thinking-star" title="思辨之星">★ 思辨之星</span>':''}`;bar.innerHTML=`<div>${left}</div><div class="v2-userbar-actions"><button class="v2-mini-btn" onclick="MTP2.shareLink()">分享当前登录链接</button>${s?'<button class="v2-mini-btn" onclick="MTP2.logout()">退出登录</button>':''}</div>`;const hero=document.querySelector('.hero');hero?.insertAdjacentElement('afterend',bar)}
function unlockTeacherView(){if(!MTP2.isTeacher())return;document.documentElement.classList.add('teacher-mode');document.querySelectorAll('.locked').forEach(el=>{el.classList.remove('locked');el.classList.add('unlocked')});document.querySelectorAll('.lock-cover').forEach(el=>el.style.display='none');document.querySelectorAll('button:disabled').forEach(b=>b.disabled=false);try{if(typeof window.unlockInquiryForTeacher==='function')window.unlockInquiryForTeacher();else{if(typeof window.unlockGallery==='function')window.unlockGallery();if(typeof window.unlockActiveInquiry==='function')window.unlockActiveInquiry()}}catch(e){}
}
function replaceBadgeEmoji(){document.querySelectorAll('.pass-badge-icon').forEach((el,i)=>{const n=(i%3)+1;if(!el.querySelector('img'))el.innerHTML=`<img src="${P.badgeFiles[n-1]}" alt="徽章${n}">`;if(MTP2.isTeacher()||MTP2.getBadge(n))el.classList.add('unlocked')});const old=document.querySelectorAll('#badge1Icon,#badge2Icon,#badge3Icon');old.forEach((el,i)=>{el.innerHTML=`<img src="${P.badgeFiles[i]}" alt="徽章${i+1}" style="width:100%;height:100%;object-fit:contain">`;if(MTP2.getBadge(i+1)||MTP2.isTeacher())el.classList.add('unlocked')})}
function addIndexSessionUI(){if(!location.pathname.endsWith('index.html')&&!location.pathname.endsWith('/'))return;const s=getSession();if(s?.role==='teacher'){const msg=document.getElementById('loginMsg');if(msg){msg.textContent='教师模式已登录：所有展馆均已解锁。';msg.style.color='#d9f2c4'}const target=document.querySelector('.teacher-link');if(target){const b=document.createElement('button');b.className='logout-btn';b.textContent='退出教师登录';b.onclick=()=>MTP2.logout();target.insertAdjacentElement('afterend',b)}}}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function patchTeacherLogin(){if(!location.pathname.endsWith('teacher.html'))return;const session=getSession();if(typeof window.checkCode==='function'){window.checkCode=function(){const input=document.getElementById('teacherCode');if(input&&input.value===P.teacherCode){setSession({role:'teacher',loginAt:new Date().toISOString()});document.getElementById('loginPanel').style.display='none';document.getElementById('dash').style.display='block';window.renderDashboard?.();addTeacherActions()}else{const m=document.getElementById('codeMsg');if(m){m.textContent='❌ 教师码错误';m.className='feedback error'}}}}
 if(session?.role==='teacher'){const lp=document.getElementById('loginPanel'),d=document.getElementById('dash');if(lp&&d){lp.style.display='none';d.style.display='block';window.renderDashboard?.();addTeacherActions()}}
}
function addTeacherActions(){const dash=document.getElementById('dash');if(!dash||dash.querySelector('.v2-teacher-actions'))return;const box=document.createElement('section');box.className='panel v2-teacher-actions';box.innerHTML='<div class="panel-title">🔐 教师模式与数据同步</div><p class="v2-cloud-note">教师登录状态会保存在当前浏览器中，直到主动退出。GitHub Pages 是静态网站；跨设备集中查看全部学生数据需要配置云数据库。当前版本支持同浏览器长期保存、JSON 导入导出，以及带登录状态的分享链接。</p><button class="btn" onclick="MTP2.shareLink()">复制教师登录分享链接</button><button class="btn" onclick="MTP2.logout()">退出教师登录</button><button class="btn" onclick="MTP2ImportData()">导入数据JSON</button>';dash.insertBefore(box,dash.children[1]||null)}
window.MTP2ImportData=function(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=()=>{const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);Object.entries(d).forEach(([k,v])=>localStorage.setItem(k,JSON.stringify(v)));alert('导入成功，页面将刷新。');location.reload()}catch(e){alert('导入失败：JSON格式错误')}};r.readAsText(f)};input.click()}
function enrichTeacherDashboard(){if(!location.pathname.endsWith('teacher.html'))return;const old=window.renderDashboard;if(typeof old!=='function'||old.__v2)return;window.renderDashboard=function(){old();const students=safeParse(localStorage.getItem('students'),'[]')||[];const activity=safeParse(localStorage.getItem('studentActivity'),'[]')||[];const holder=document.getElementById('studentTable');if(holder){holder.innerHTML='<tr><th>年段</th><th>班级</th><th>座号</th><th>姓名</th><th>探展编号</th><th>最近登录</th><th>徽章</th><th>思辨之星</th><th>活动记录</th></tr>'+students.map(s=>{const count=activity.filter(a=>a.studentKey===s.key).length;const badges=(s.badges||[]).filter(Boolean).length;return `<tr><td>${escapeHtml(s.grade||extractGrade(s.cls))}</td><td>${escapeHtml(s.cls)}</td><td>${escapeHtml(s.seat)}</td><td>${escapeHtml(s.name)}</td><td>${escapeHtml(s.passNumber||'')}</td><td>${escapeHtml(s.lastLogin||s.time||'')}</td><td>${badges}/3</td><td>${s.thinkingStar?'已点亮':'—'}</td><td>${count}</td></tr>`}).join('')||'<tr><td colspan="9">暂无学生记录</td></tr>'}
 const panels=document.querySelectorAll('#dash .panel');if(!document.getElementById('gradeSummary')){const p=document.createElement('section');p.className='panel';p.id='gradeSummary';p.innerHTML='<div class="panel-title">🏫 年段与班级情况</div><div id="gradeSummaryBody"></div>';const studentPanel=[...panels].find(x=>x.textContent.includes('学生学习记录'));studentPanel?.insertAdjacentElement('beforebegin',p)}const body=document.getElementById('gradeSummaryBody');if(body){const groups={};students.forEach(s=>{const g=s.grade||extractGrade(s.cls),c=s.cls||'未分班';groups[g]??={};groups[g][c]=(groups[g][c]||0)+1});body.innerHTML=Object.keys(groups).length?Object.entries(groups).map(([g,cs])=>`<div class="card" style="margin-bottom:12px"><b>${escapeHtml(g)}</b>：${Object.entries(cs).map(([c,n])=>`${escapeHtml(c)}（${n}人）`).join('　')}</div>`).join(''):'<div class="empty">暂无年段与班级数据</div>'}
};window.renderDashboard.__v2=true}
function sortEnhance(){if(!location.pathname.endsWith('inquiry.html'))return;const grid=document.getElementById('stepGrid');if(!grid)return;let drag=null;const prepare=()=>{[...grid.children].forEach(card=>{card.draggable=true;card.ondragstart=e=>{drag=card;card.classList.add('v2-dragging');e.dataTransfer.effectAllowed='move'};card.ondragend=()=>{card.classList.remove('v2-dragging');drag=null};card.ondragover=e=>e.preventDefault();card.ondrop=e=>{e.preventDefault();if(!drag||drag===card)return;const arr=[...grid.children],a=arr.indexOf(drag),b=arr.indexOf(card);if(a<b)grid.insertBefore(drag,card.nextSibling);else grid.insertBefore(drag,card);syncOrder()}})};const syncOrder=()=>{try{if(Array.isArray(window.currentOrder))window.currentOrder=[...grid.children].map(c=>c.dataset.id||c.getAttribute('data-id')||c.textContent.trim()).map(v=>isNaN(v)?v:Number(v))}catch(e){}};new MutationObserver(prepare).observe(grid,{childList:true});prepare();const hint=grid.parentElement?.querySelector('.muted');if(hint)hint.textContent='点击一张卡片，再点击另一张可交换位置；也可以直接拖动卡片完成排序。'}

function refreshThinkingStarUI(){
 const old=document.querySelector('.v2-userbar');if(old){old.remove();addUserBar()}
 try{if(typeof window.renderStudentPass==='function')window.renderStudentPass()}catch(e){}
 document.querySelectorAll('.thinking-star-mark').forEach(el=>el.classList.add('unlocked'));
}
document.addEventListener('mengxiThinkingStarUnlocked',()=>setTimeout(refreshThinkingStarUI,0));

function mediaCheck(){document.querySelectorAll('video source').forEach(s=>{if(!s.src&&s.dataset.src)s.src=s.dataset.src});}
document.addEventListener('DOMContentLoaded',()=>{patchFunctions();moveNavIntoHero();addUserBar();addIndexSessionUI();patchTeacherLogin();enrichTeacherDashboard();unlockTeacherView();replaceBadgeEmoji();sortEnhance();mediaCheck();setTimeout(()=>{unlockTeacherView();replaceBadgeEmoji()},350)});
})();
